ageitgey/face_recognition

requirements.txt, setup.py
=> Add Pillow as a dependency and bump version

tests/test_face_recognition.py
This PR brings the test module into PEP8 compliance and makes
use of the Unittest's native asserts.
=> Refactor Tests

.travis.yml, face_recognition/cli.py, setup.cfg, setup.py, tests/test_face_recognition.py, tox.ini
Replaces test command in .travis.yml so tests get run. Updates
Flake8 configuration. Adds Tox to handle testing of multiple Python
versions. Adds test dependencies to setup.py. Fixes bug in test.
=> Fix For Travis Test Step

face_recognition/__init__.py, face_recognition/api.py, tests/test_face_recognition.py
=> Expose face_distance and prevent errors with empty inputs

README.md, examples/web_service_example.py
A simple example of using Flask to host a web service that recognizes faces in images.
Fixes #40
=> Add webservice example

HISTORY.rst, face_recognition/api.py, setup.py, tests/test_face_recognition.py
- Fix missing chin points
- Bump version
Fixes #48 
Replaces #49 
Replaces #50
=> Fix missing chin points

README.md, face_recognition/cli.py, tests/test_face_recognition.py
If you pass in `--cpus <number_of_cpus>` to the CLI, it will run face recognition in parallel across multiple cpus.
=> All support for parallel processing in the CLI

README.md, examples/face_distance.py
This is a re-worked version of #108.
=> Add face distance example

README.md, face_recognition/cli.py, setup.py, tests/test_face_recognition.py
To help address #129 
You can now add `--tolerance 0.54` to the CLI to specify a custom tolerance value.
=> Allow custom tolerance values in CLI application

HISTORY.rst, README.md, face_recognition/cli.py, setup.py, tests/test_face_recognition.py
=> Add --show-distance parameter to CLI

examples/facerec_from_video_file.py, examples/facerec_from_webcam.py, examples/facerec_from_webcam_faster.py, examples/find_faces_in_batches.py, setup.py, tox.ini
Fix #271 
OpenCV works in BGR color. So when using OpenCV to capture images in the examples, make sure we convert it to RBG before passing it to face_recognition.
=> OpenCV input fix

.github/ISSUE_TEMPLATE.md
Hopefully, this will save you some time ;-)
=> Ask for sample image in Issue template

examples/facerec_from_webcam.py, examples/facerec_from_webcam_faster.py, examples/recognize_faces_in_pictures.py
- Extend webcam examples to detect multiple different faces (Fix #323)
- Catch IndexError in face recognition example
=> Update examples to reduce questions

README.md
=> spelling fix - instuctions -> instructions

HISTORY.rst, examples/face_recognition_knn.py
- Clean up code style in KNN example
- Fix a bug where the KNN example could crash when trying to label images due to PIL issues
=> Clean up KNN example

examples/find_facial_features_in_picture.py, face_recognition/api.py, tests/test_face_recognition.py
#470 added support for using the 5-point facial feature extraction model from the `face_landmarks()` function.
These are minor updates to support that:
- Update doc strings
- Add a test
- Update example so it doesn't break if you use the 5-point model
FYI @Vermeille
=> Small updates to support #470

HISTORY.rst, examples/find_facial_features_in_picture.py, face_recognition/__init__.py, setup.py
- Bump version
- Fix small issue in facial feature demo (opening multiple windows instead of one for multiple faces in same image)
=> Version 1.2.3

Dockerfile, Dockerfile.gpu, README.md, docker-compose.yml
After several hours trying to run face_recognition on the GPU, I created this Dockerfile with Dlib installed + CUDA and cuDNN. Ready to use on the GPU with Nvidia-Docker.
It can dramatically reduce the number of issues regarding the usage on the GPU.
Full example: https://github.com/enric1994/face_recognition_docker_gpu
=> GPU support for Docker

face_recognition/api.py
Some image file is truncated may cause PIL load image error
See: https://stackoverflow.com/a/23575424 for more information
=> Fix PIL error "OSError: image file is truncated"

examples/facerec_from_webcam.py, examples/facerec_from_webcam_faster.py, examples/identify_and_draw_boxes_on_faces.py
I was using the example codes and got a very low accuracy recognizing faces. Interestingly, many people in the photo are being recognized as the same person, who is also the first person in the known arrays. I found out that instead of picking the first face in the known faces that have small enough distance, directly using the face with the smallest distance yields a much better result.
=> Use the best match for better accuracy in examples

README.md
Hi, it took me a while to get it up and running, so I created a demo on Deepnote. Adding here in case anyone else would find it useful.
=> Add an online demo

README_Korean.md
To actively participate of Korean contributors, I have translated the 'README.md' file into Korean.
The 'README_Korean.md' file is translated in Korean.
If you like this translation, I would like to have a link for 'README_Korean.md' in 'README.md' with merge.
'README_Korean.md' file is translated by sgc0907.
Thanks.
=> Create README_Korean.md file

examples/face_recognition_svm.py
Hi,
It's an example using SVC and scikit-learn to train multiple images per person and recognizing faces from a test image.
:)
=> Added an example for recognizing faces using a SVM

README.md, examples/face_recognition_svm.py
Updated readme with an added example of using a SVM classifier to train multiple images per person and recognize them from an image.
=> Added an example with a SVM classifier to readme

examples/face_recognition_svm.py
Show a message if a training image contains none or more than one faces
=> Show a message if no faces in training image

examples/facerec_from_webcam_multiprocessing.py
This applies #826 by @chn-lee-yumi manually because the git history in the PR was messed up.
Original PR #826 is to fix #809.
=> Applying changes from #826 by chn-lee-yumi manually due to bad git history in PR

face_recognition/api.py
In doc: parameter img fix to images as function parameter.
=> Fix docstring in face_recognition.api.batch_face_locations

face_recognition/api.py, tests/test_face_recognition.py
This PR is a feature enhancement that allows the `face_encodings` function to accept using either the 'large' or 'small' model for pose prediction.
=> Allow `face_encodings` to accept either 'large' or 'small' pose prediction models

examples/blink_detection.py
Added an example that allows users to detect when a persons eyes are closed for a certain length of time. This code implements the idea found in this paper - http://vision.fe.uni-lj.si/cvww2016/proceedings/papers/05.pdf and should run out of the box.
=> added blink detection example

README.md, README_Japanese.md
Hi!
I have just created README_Japanese.md file.
I hope many Japanese developer use this library.
Issue: #1009 
thanks!
=> Create README_Japanese.md file

face_recognition/face_detection_cli.py
Otherwise smaller faces can't be located via command line
=> Make --upsample a parameter for command line face_recognition

face_recognition/api.py
Just a quickfix on some docstrings in the `face_recognition/api.py` file.
=> Fix docstrings in api.py
