ageitgey/face_recognition

HISTORY.rst, requirements.txt, setup.py
`scipy >= 0.17.0` is required or image loading will fail due to `scipy` not supporting the `mode` parameter.
=> Scipy version fix

face_recognition/api.py
From http://stackoverflow.com/questions/7741878/how-to-apply-numpy-linalg-norm-to-each-row-of-a-matrix
Running time comparisons (prev vs. new, performed using faces = np.random.rand(n, 128), face_to_compare = np.random.rand(1, 128))
n = 1M:  5.3s vs. 1.1s
n = 5M:  26.9s vs. 6.6s
n = 10M: 52.6s vs. 23s
=> Replace _face_distance with more efficient calculation

face_recognition/cli.py
In the CLI, if a known_image contains no faces it currently cases because this `else` statement was missing.
Fixes #34
=> Ignore known files with no faces in CLI

face_recognition/cli.py
If `unknown_image.shape[1] > 1600` then `scale_factor` will be always calculated `0` because `1600 / unknown_image.shape[1]` is an `int` over `int` division which in turn will always raise a ValueError in `PIL.Image.resize`. Making `1600` a float (1600.0) fixes the issue.
=> Convert 1600 to a float.

face_recognition/api.py
Because face_recognition.load_image_file simply wraps scipy.misc.imread, it is also possible for load_image_file to take a file object, not just a filename.
Clarify this in the api by renaming filename to name and adjusting the docstring, in accordance to scipy.misc.imread.
I am not 100% sure about the renaming of the parameter though since it is an API breakage, if a mild one. Maybe just adjusting the docstring and skipping the rename of the parameter is the better option here.
=> Clarify that file object is also a valid parameter to load_image_file

Dockerfile, HISTORY.rst, README.md, README.rst, examples/recognize_faces_in_pictures.py, face_recognition/api.py, setup.py
- Bump version to 1.1.0
- Require dlib 19.7 and face_recognition_models 0.3.0
- Support the new slimmer 5-point face post model when creating face encodings. This speed things up slightly (a few fps in some cases)
- Update docs/Dockerfile everywhere to say dlib 19.7 instead of dlib 19.5
See http://blog.dlib.net/2017/09/fast-multiclass-object-detection-in.html for context on dlib speed-ups
Now that redundant face pose models are being loaded, it makes sense to start lazy loading them to save ram (especially on an RPi). But I didn't do that yet because I haven't tested how it might interact with python's different multiprocessing modes when using more than one thread.
=> Support for new dlib 19.7 stuff

face_recognition/api.py
Changed the spelling of "dimentional" to "dimensional" in comments section of api.py file .
=> Corrected the spelling in api.py file.

face_recognition/api.py
`batch_size` variable in `batch_face_locations ` function was not passed to `_raw_face_locations_batched `. Also `_raw_face_locations_batched ` lack input `batch_size` variable to pass into dlib's `cnn_face_detector`.
Above lacks are added in this PR
=> make batch_size effective in _raw_face_locations_batched

docs/conf.py, face_recognition/__init__.py, face_recognition/api.py, face_recognition/cli.py, setup.cfg, setup.py, tests/test_face_recognition.py
Remove scipy dependency because it's not really needed, it's hard to install on windows, and it's a common source of help requests.
See for reference: #382
Fixes: #363
Fixes: #301
Fixes: #242
Fixes: #103
Fixes: #6
Fixes: #10
=> Remove scipy dependency and bump version

face_recognition/face_recognition_cli.py
add no_persons_found to face recognition command line. This allows feedback for all images, otherwise images with no detections are not reported on.
=> added no_persons_found to face recognition command line

face_recognition/api.py
Hello Adam,
This is a small change to allow reading the landmarks from the small model (especially useful for debugging face alignment).
It would be better, for consistency, to return the landmarks as a dict, like for the 68 points models, but I couldn't find which point was what (and I prefer to have them as a list for my usage anyway). If you know where to find that information, I'll gladly update that PR.
Have a nice day!
=> extract landmarks from the small model

.travis.yml
CI build (all python interpreter versions) passed, following link provided below:
https://travis-ci.org/duboviy/face_recognition
[Additional Note]:
Right now Python 3.7 version can't be simply added (without specifying 'xenial' dist & sudo) due to Travis-CI issue:
https://github.com/travis-ci/travis-ci/issues/9815
So I'd suggest to use following changes before Travis-CI issue is fixed as it's done in other big python projects with 3.7 python support.
=> Add Python 3.7 version support

Dockerfile.gpu
[DLIB](https://github.com/davisking/dlib) repository removed the `--yes` option on the setup.py:
https://github.com/davisking/dlib/commit/b892df823268446012ff9717ed9544cfa891a30b
Using `--yes USE_AVX_INSTRUCTIONS --yes DLIB_USE_CUDA` generates the following error:
```
Step 13/14 : RUN cd /dlib; python3 /dlib/setup.py install --yes USE_AVX_INSTRUCTIONS --yes DLIB_USE_CUDA
---> Running in 7746a50797fd
The --yes options to dlib's setup.py don't do anything since all these options 
are on by default.  So --yes has been removed.  Do not give it to setup.py.
ERROR: Service 'face_recognition' failed to build: The command '/bin/sh -c cd /dlib; python3 /dlib/setup.py install --yes USE_AVX_INSTRUCTIONS --yes DLIB_USE_CUDA' returned a non-zero code: 1
```
=> DLIB build removed the --yes option: Dockerfile updated

examples/digital_makeup.py
This fix allows for makeup to be applied to all faces in the image. The previous version would only apply makeup to one face since the new base image would be created each time loop would start.
=> Example fix for multi-face images.

examples/facerec_from_webcam_multiprocessing.py
This PR offers a bug fix for the multiprocessing-based webcam face recognition demo. Occasionally, when the user requests to quit the demo, the camera worker will close before the face recognizer processes, which can cause them to keep waiting for frames to process when there are none.
This bug fix fixes that issue by checking if the user has requested to quit the demo while waiting for more frames to process and exiting when that's the case.
=> Fixed occasional "zombie" processes from running `facerec_from_webcam_multiprocessing.py`

Dockerfile
Old apt-get`libatlas-dev` updated to it's new `libatlas-base-dev` reference in the example Dockerfile.
=> Dockerfile example libatlas-dev update

pyproject.toml
The configuration under `[build-system]` inside of `pyproject.toml` specifies the _build-time_ dependencies, which are setuptools and wheel for this project. They may seem obvious to have but there are some cases in which they aren't present (e.g., inside a Docker container, that they try to be minimal in size). This makes `pip install face_recognition` first install these dependencies before installing itself. See [PEP 518](https://www.python.org/dev/peps/pep-0518/).
=> Add build-system dependencies

examples/face_recognition_knn.py, examples/facerec_ipcamera_knn.py
There is a small typo in examples/face_recognition_knn.py, examples/facerec_ipcamera_knn.py.
Should read `euclidean` rather than `eucledian`.
=> docs: Fix simple typo, eucledian -> euclidean

examples/blink_detection.py
In the blink detection script, there were 2 problems. 
The first problem was quitting the script. Since the cv2.waitKey() was inside the for loop that processes the facial landmarks, we can not quit the script. It should be moved outside the for loop. I assigned "q" for exiting the script.
The second problem was the keyboard module. Using keyboard module in Linux causes the following error: "ImportError: You must be root to use this library on linux."
I replaced kb.is_pressed('space') with cv2.waitKey(1) == 32
=> Blink detection fix

README.md, docker/Dockerfile-python-example, docker/README.md, docker/cpu-jupyter-kubeflow/Dockerfile, docker/cpu/Dockerfile, docker/gpu-jupyter-kubeflow/Dockerfile, docker/gpu/Dockerfile
I've reworked the Docker images a bit to get them up to date. Here's a summary of my changes:
- Upgraded dlib to v19.21
- Upgraded the GPU base image to use cuda 11 and cudnn8 (`nvidia/cuda:11.2.0-cudnn8-devel`)
I. Its has been supported by dlib for around [~6 months](https://github.com/davisking/dlib/issues/2100#issuecomment-670699524)
II. There are several performance gains from this upgrade.
- Implemented multi-stage builds to shrink image sizes.
I. The CPU image went from ~2GB to 350MB
II. The GPU image went from ~7GB to ~4GB
- Added a Kubeflow Jupyter image for easy development on platforms like GCE. 
I've setup some autobuilds to keep these images up-to-date. I'm currently hosting these images on [my docker hub](https://hub.docker.com/repository/docker/animcogn/face_recognition). I …
=> docker refactor

examples/facerec_ipcamera_knn.py
The third last line (line no. 212) is written as cap1.release(). It should be cap.release instead.
cap1.release() > cap.release()
=> There is a typo in face_recognition/example/facerec_ipcamera_knn.py
